### ISSUE TITLE
Page buttons not added to bottom

### ISSUE THREAD

**Issue by syphernl** [nikku/jquery-bootstrap-scripting#1]
I am trying to rebuild your "Check out running example" sample 2, by having the form's buttons put in the bottom of the form. Somehow, it is not doing this.

Example of what happens:
http://img16.imageshack.us/img16/7310/testcaj.png

**Comment by syphernl** [comment]
Hmm, for some reason the page did not include the ajaxform plugin. Either way, it should not rely on this solely to put the buttons there, for that I've created a "feature request" in #2

**Comment by nikku** [comment]
What is the exact markup you are using?
The HTML markup I am using is

``` html
        <title>jQuery dialog2 plugin</title>


        <h1 style="display: none; ">Thanks :-)</h1>
        <p>
            Thanks for clicking the previous link. May you tell me your name?
        </p>
        <form class="ajax" method="get" action="finish.html">
            <fieldset>
                <div class="clearfix">
                    <label for="name">Your name</label>
                    <div class="input">
                        <input type="text" name="name" id="name">
                    </div>
                </div>
            </fieldset>
            <div class="actions" style="display: none; ">
                <input type="submit" value="Send" class="btn">
            </div>
        </form>
```

which will, as a `.ajax` annotated form is found, hide the form submit area (`div.actions`) and create a submit button on the dialog.
