### ISSUE TITLE
z-index problem on ajax loaded content

### ISSUE THREAD

**Issue by skattabrain** [nikku/jquery-bootstrap-scripting#12]
The modal window using the ajax class is taking a higher z-index priority over jquery ui.

http://artistcolony.skattabrain.com/ - if click the blue Register button, you will see the issue as it pulls in the page. Clicking the "Date Of Birth" Field

**Comment by nikku** [comment]
Could you try see if the issue persists if you use the [new version of the script](https://github.com/Nikku/jquery-bootstrap-scripting/tree/v1.1.0)? The structure of the dialog / overlay changed.

Generally jquery-ui adjusts the `z-index` property of the date picker to be one higher than the input it is bound to.
In the context of the modal dialog, this might not work for `life()` registered date picker bindings as you use them. 

I may be wrong though.

**Comment by skattabrain** [comment]
Nikku, your update fixes the z-index problem, thank you!
