### ISSUE TITLE
Wrong Class for Automatic Links

### ISSUE THREAD

**Issue by przeroone** [nikku/jquery-bootstrap-scripting#15]
In the doc, it said "a.ajax links within the dialog content will trigger loading of a new dialog page inside the dialog.". After checking for the source file, it should be "a.open-dialog".

**Comment by nikku** [comment]
No, that actually correct, but inconsistent.

When using the `jquery.controlls` plugin the open dialog functionality will be attached to `a.open-dialog`. Inside a dialog, in-dialog navigation is done on `a.ajax` links and `form.ajax` forms.

Will leave that open as I should rename the ajax to in-dialog-navigation or something in the next release.

**Comment by przeroone** [comment]
Got it!

Thanks for your explanation and hard work, this project is a good one! :-)
