### ISSUE TITLE
Cancel button disappears when using custom buttons

### ISSUE THREAD

**Issue by syphernl** [nikku/jquery-bootstrap-scripting#16]
In the latest version, the cancel button disappears after loading is complete, and when the custom buttons (from class 'actions') are moved to the bottom of the modal.

**Comment by nikku** [comment]
That is the new default behaviour. 

It is easy to add your own cancel button `<a class="btn close-dialog" href="#">Cancel</a>`.

**Comment by nikku** [comment]
Closing this issue.
