### ISSUE TITLE
Feature request: should close with esc key

### ISSUE THREAD

**Issue by andreslucena** [nikku/jquery-bootstrap-scripting#18]
Most modals have 3 ways to close: 
- Clicking outside (OK)
- Clicking in close button (OK)
- Pressing esc key (KO)

So, it would be a nice feautre to have.

**Comment by nikku** [comment]
Seems to be a duplicate of #11.

**Comment by andreslucena** [comment]
woop, sorry about that. It seems and it is. Keep up with the magic :)
