### ISSUE TITLE
auto closing on final confirmation

### ISSUE THREAD

**Issue by jerzyk** [nikku/jquery-bootstrap-scripting#19]
It may be useful to have an option to automatically close after successful form submission.

My idea is to add handling of the "close" button, adding this code at the beginnig of `__ajaxify` function:

```
            var autoclose = e.find("a.auto-close");
            if (autoclose.length > 0) {
                this.close();
                var href = autoclose.attr('href');
                if (href)
                    window.location.replace(href);
                return
            }
```

This will allow to have additional class in te markup of the final "confirmation page":

```
<a class="btn close-dialog auto-close" href="/go-to-here">Close</a>
```

if `href` will be empty - it will just close a dialog, if not - main page will reload with specified URL as destination.

**Comment by nikku** [comment]
Sorry for the late response. 

You can add your own behavior to a dialog by attaching event listeners to it.
Currently the dialog fires `dialog2.ajax-start`, `dialog2.ajax-complete` and `dialog2.content-update`.

The right event is `dialog2.content-update` is the event you could listen to to add the stuff you described as a plugin.

You could use the following snipped to do that.

``` javascript
$(document).delegate(".modal", "dialog2.content-update", function() { 
     // got the dialog as this object. Do something with it!
});
```

**Comment by nikku** [comment]
See updated [README](https://github.com/Nikku/jquery-bootstrap-scripting/blob/master/README.md).
