### ISSUE TITLE
Option to put all custom buttons in footer

### ISSUE THREAD

**Issue by syphernl** [nikku/jquery-bootstrap-scripting#2]
It would be nice if we can have an option that automatically puts all buttons, either with the "btn" class or inside "actions" class and with "btn" class, in the footer of the modal box.

**Comment by nikku** [comment]
Nice idea, will implement that in the next release :-)

**Comment by syphernl** [comment]
Adding this after the dialog.find for h1 works sort-of (I am not really a jQuery programmer)

```
        dialog.find(".actions a.btn").each(function (index, domEle) 
        {
            $('.modal-footer').append( $(domEle) );
        });
```

**Comment by syphernl** [comment]
Better code, append this to __ajaxCompleteTrigger so that it also works on ajaxed pages:

```
        $(this).find("a.btn").each(function (index, domEle)
        {
            $('.modal-footer').append( $(domEle) );
        });
        $(this).find("input[type=submit].btn").each(function (index, domEle)
        {
            $('.modal-footer').append( $(domEle) );
        }); 
```

Still needs some tweaking though, but getting there :-)

**Comment by nikku** [comment]
Fixed in new version of the script (along with #3). Check out the new samples on 
http://nikku.github.com/jquery-bootstrap-scripting
