### ISSUE TITLE
autoOpen set to false is not being obeyed on onpage div... modal opens on page load

### ISSUE THREAD

**Issue by skattabrain** [nikku/jquery-bootstrap-scripting#20]
Having an issue, not sure if what I'm doing it incorrect... have tried it several ways but autoOpen is not being obeyed.

a class="open-dialog" rel="export_companies" autoOpen="false"

div style="display: none;" id="export_companies"

I've also tried this...

```
    $("#export_companies").dialog2({
        showCloseHandle: false,
        removeOnClose: false, 
        autoOpen: false, 
        closeOnEscape: false, 
        closeOnOverlayClick: true
    });

    $("#test").click(function(event) {
        event.preventDefault();
        $("#export_companies").dialog2("open");
    });
```

**Comment by nikku** [comment]
Solved?

**Comment by skattabrain** [comment]
Yes I apologize... actually for the in page modal divs I'm just going with Twitters modal solution. But your AJAX solutions have been working out fantastic... thank you for this script!
