### ISSUE TITLE
Can't get automatic linking to work

### ISSUE THREAD

**Issue by jahvi** [nikku/jquery-bootstrap-scripting#21]
Hi, I've been having problems trying to set up automatic links, I have this link:

``` html
<a href="test.php" class="open-dialog" rel="my-modal">Link</a>
```

Which in theory should show me the contents of my `test.php` file in a modal window but instead it just takes me to that page like normal, if I call the modal plugin using JS it works fine, I'm using jQuery 1.6.4 and the latest controls and dialog2 plugins.

I used some `alerts()` to test if the dialog2 plugin was recognizing the controls plugin and it does so I'm not sure if I'm doing something wrong here.

**Comment by syphernl** [comment]
Automatically ajaxifying the links is done via the [jQuery Controls plugin](https://github.com/Nikku/jquery-controls). I'm using the bottom Javascript example in my own projects.

**Comment by nikku** [comment]
@syphernl is right, you have to use the controls plugin in conjunction with the following javascript snipped.

``` javascript
<script type="text/javascript">
    // Wait for page load
    $(function() {
        // Bind to document
        $(document).controls();
    });
</script>
```

Going to close this issue. Tell me, if you have any more problems.
