### ISSUE TITLE
popover

### ISSUE THREAD

**Issue by studeba** [nikku/jquery-bootstrap-scripting#24]
I wonder, can the same thing be done with the bootstrap popover? 

Ajax content
Ajax links and form submission in the dialog
Loading indicator

**Comment by nikku** [comment]
Well, the popover is not exactly the focus of this plugin. Possible is everything though = )

**Comment by shouze** [comment]
studeba  : I wonder it you've already done it or not ?

**Comment by nikku** [comment]
No, have not done any work yet.
Looks like it is a bigger issue. You can fork my project and implement it if you like to.
Pull requests are welcome :-).
