### ISSUE TITLE
Add bootstrap 2.0 support.

### ISSUE THREAD

**Issue by nikku** [nikku/jquery-bootstrap-scripting#27]

**Comment by skattabrain** [comment]
Hi Nikku, just wondering what your plans are on BS2 support? I've come to depend on this awesomess, I just tried and miserably failed getting this going with BS 2.0.1

**Comment by nikku** [comment]
Bootstrap 2 Support is next on schedule (see https://github.com/Nikku/jquery-bootstrap-scripting/issues/milestones)
Cannot promise anything but will try to look into that at the Weekend. 

Any ideas what has to be done to achieve BS 2.0 support?

**Comment by nikku** [comment]
Implemented bootstrap 2 support in 2.0-wip branch.
Check it out and tell me what you think :-).

**Comment by skattabrain** [comment]
Thanks Nikku, for me it will be next project... I had to improvise for this one, thanks for the update!

**Comment by tboyko** [comment]
What sort of issues are addressed in the upgrade/branch? I'm using the main branch and haven't run into any issues yet (save for the enter key causing forms to submit, which might still be an implementation-specific issue of mine).
