### ISSUE TITLE
can't use content and buttons simultaneously

### ISSUE THREAD

**Issue by itbros** [nikku/jquery-bootstrap-scripting#28]
When I set content option for ajax and buttons,
I can't see buttons.

After removing content option,
I can see buttons.

Help, please!

Thank you for making great plugins!

**Comment by nikku** [comment]
Can you provide an example for the issue? Thanks! :-)

**Comment by nikku** [comment]
Was able to reproduce the issue.

The reason why you cannot use content and buttons simultaneously is that the ajax result is supposed to override the dialogs buttons (see http://nikku.github.com/jquery-bootstrap-scripting/). 

The right way to use buttons in conjunction with ajax load is to (a) specify the buttons later (when the ajax content has been loaded) or to (b) encode the buttons in the ajax response.
