### ISSUE TITLE
Tab key navigation restriction

### ISSUE THREAD

**Issue by Jito** [nikku/jquery-bootstrap-scripting#30]
When the modal is opened, if you press `Tab` or `Shift + Tab` you can focus all the underlying elements.

From a UX point of view, if the purpose of a modal is to **catch** the user's attention and get _something_ resolved through an action, so it would be extremely useful to restrict the tab key navigation to the focusable elements of the modal.

A quick approach to the logic behind it could be:
1. Listen to the `keydown` event in the modal DOM element (childs will bubble up)
2. Check each time that the focused element is one of the modal's children
3. If it's not, return focus to the first focusable element (link, input or button)

**Comment by nikku** [comment]
Nice catch. Will schedule that for 2.0 of the plugin.

**Comment by davistan** [comment]
Is this issue fixed? I've tried tabbing on the demo pages in Chrome but the focus still works for background tabbable controls. I've found this plugin which works - http://julienw.github.com/jquery-trap-input/

**Comment by nikku** [comment]
Should be fixed on 2.0 branch.
