### ISSUE TITLE
onClose callback

### ISSUE THREAD

**Issue by Jito** [nikku/jquery-bootstrap-scripting#31]
It would be handy a callback function fired when the user exits the modal with the `Esc` key, without pressing any action button.

**Comment by nikku** [comment]
There exist 

```
$("dialog").bind("dialog2.closed", function(event) {
    alert("Dialog was closed");
});
```

Does that help?

**Comment by Jito** [comment]
And how could I do that if I'm using the helpers? I mean, in that scenario there's no object I'm attaching the bind method to.

**Comment by nikku** [comment]
Sorry for the late response!

The call to `$.fn.dialog2.helpers.alert("This dialog is non intrusive", { ... }")` does return the dialog 2 dom element. You can freely bind your event listeners against it (e.g. `var dialog = $.fn.dialog2.helpers.alert(...); dialog.bind("dialog2.closed", ...);`.
