### ISSUE TITLE
Modals not being removed upon close

### ISSUE THREAD

**Issue by tboyko** [nikku/jquery-bootstrap-scripting#32]
I am using html markup to create modal links via `a.ajax` and running `$(document).controls();` on document load. When I close modal windows, the `.modal` div still exists in the DOM, which is causing issues for me. `.modal-backdrop` and `.modal-body` are being removed, but not `.modal`.

Perhaps this behavior is desirable for non-ajax implementations, or perhaps this is a bug. Feedback?

**Comment by nikku** [comment]
Good call!
Fixed in 1.2-wip.
