### ISSUE TITLE
JSON response

### ISSUE THREAD

**Issue by synned** [nikku/jquery-bootstrap-scripting#36]
Is there any way to get JSON response after form submission and do something with it on "dialog2.ajax-complete"?
Sometimes I need my callbacks to do several things depending on response (for example, update table row after it's been edited, update &lt;select&gt; list in "parent" form after I add/edit an item using modal form, etc...).

**Comment by synned** [comment]
Actually, never mind, I found an easy way to do it.
Removed "ajax" class from &lt;form&gt; to prevent dialog2 from axifying it, and then I did something like this:

<pre>
$(document).on('submit', '.modal form', function(e){
  e.preventDefault();
  var form = $(this);
  var dialog = form.parents('.modal-body');
  form.ajaxSubmit({
    success: function(response){
      if (typeof response == 'object') // response is JSON
      {
        dialog.close();
        // do whatever
      }
      else
      {
        // update dialog content
        dialog.html(response);
        dialog.trigger('dialog2.content-update');
      }
    }
  });
});
</pre>

**Comment by nikku** [comment]
Yes, that is exactly how you do it.
