### ISSUE TITLE
How can I remove Cancel button?

### ISSUE THREAD

**Issue by sjoonk** [nikku/jquery-bootstrap-scripting#40]
When I popup this dialog, it always show a "Cancel" button at the bottom right of the window.
I'd like to remove this button.
Please let me know how can I remove this Cancel button.
I've read this library's document, but I can't find the solv.

Thanks in advance.

**Comment by nikku** [comment]
You can remove the button labled `Cancel` manually by calling `$(dialogElement).dialog2("removeButton", "Cancel");`.
If you want to disable adding cancel buttons automatically you can set `$.fn.dialog2.defaults.autoAddCancelButton` to `false`.
