### ISSUE TITLE
error when option 'content' has selector

### ISSUE THREAD

**Issue by peterdds** [nikku/jquery-bootstrap-scripting#48]
I want to load page from server and I use 'content':'url #selector", but an error occurs. I see the code the var rscript is not defined.  is that should be ''' responseText.replace(/<script(.|\s)*?\/script>/g, "")
// to avoid any  Permission Denied errors in IE

<pre>.append( responseText.replace( rscript, "" ) )</pre>

**Comment by nikku** [comment]
If your proposal is already the solution, could you file a pull request?
Thanks!
