### ISSUE TITLE
Dialog is displayed on load

### ISSUE THREAD

**Issue by rboarman** [nikku/jquery-bootstrap-scripting#50]
My dialog is being displayed even though I have style="display: none" for the style.

Here's an example:

http://jsfiddle.net/rboarman/WLpky/

What am I doing wrong?

**Comment by bmichalski** [comment]
Hi,

I've had the same problem with an onpage div.
Adding style="display: none;" on line 26 in jquery.dialog2.js seems to fix it.

``` javascript
var __DIALOG_HTML = "<div class='modal' style=\"display: none;\">" + 
```

**Comment by rboarman** [comment]
Worked for me too. Thanks! How do we get it fixed in the repository?

**Comment by nikku** [comment]
Write a pull request? :-P
