### ISSUE TITLE
Pass data to modal

### ISSUE THREAD

**Issue by afanjul** [nikku/jquery-bootstrap-scripting#51]
Hello, is it possible to pass data to modal window from several links that open the modal? For instance: a list of people with a link for each one to open a modal with profile data. 

For bootstrap this feature is being requesting by many people and somebody wrote a patch for add it, could you add it too?

https://github.com/twitter/bootstrap/issues/531

thanks in advance,
Alex

**Comment by nikku** [comment]
If that is an issue you are running into, would you mind to submit a pull request. 
Do not quite see the point of https://github.com/twitter/bootstrap/issues/531. 

Cheers, 
Nico
