### ISSUE TITLE
BUG? document.write(variable); opens new page

### ISSUE THREAD

**Issue by solver80** [nikku/jquery-bootstrap-scripting#54]
If I add to example notice.html code:

`var ids = "text";
document.write(ids);`

The modal will open for about 1sec, and you will see variable "text" printed. 
Than new page will open and you will see exacly same thing as on your modal.

**Comment by nikku** [comment]
Why are you using `document.write()`? Have not seen it for quite some time to be honest.

**Comment by solver80** [comment]
It's just for purpose of seeing if the modal will display copied variable

**Comment by nikku** [comment]
Well, I guess `document.write()` should just not be used in state-of-the-art web development.
