### ISSUE TITLE
Response Text with Ajax Button

### ISSUE THREAD

**Issue by kevinmeckl** [nikku/jquery-bootstrap-scripting#56]
Hello,

a form send via ajax the values to a PHP Script and return a Sucess or Wrong text.
In the text was output is a ajax link to come in the next modal.

The ajax link was response load is not work.
But a ajax link was directly in the modal works. Why?

Thank You

**Comment by nikku** [comment]
Cannot reproduce with a precise description. Could you file in the source code you are using?

**Comment by kevinmeckl** [comment]
I try again. The ajax button is loaded later than the modal box. The ajax button will only be charged at an action and displayed. The ajax button works but then does not. Only when the ajax button is displayed directly to the modal box.

What can I do, or is it even possible?
