### ISSUE TITLE
Call Dialog from a iframe

### ISSUE THREAD

**Issue by ghost** [nikku/jquery-bootstrap-scripting#59]
Hi, is there a fix for the script that makes it possible to show the dialog on top of the current screen, if it's called from a iframe. Now it opens inside the iframe, but I'd like the dialog to open in the current screen, over the whole window.

``` html
<div style="padding:100px;background:#ddd"> 
<iframe src="http://nikku.github.com/jquery-bootstrap-scripting/" 
width="500px" height="500px"> </iframe>
</div>
```

**Comment by nikku** [comment]
There is no fix for that. Elements inside i-frames can never reach out of the iframes as far as I know.

I would discourage you from using iframes in modern web applicaitons anyway.
