### ISSUE TITLE
Can't pass HTML button contents to modal

### ISSUE THREAD

**Issue by TomCrowley** [nikku/jquery-bootstrap-scripting#66]
I noticed that I can't include icons inside my buttons. This is especially useful if your design is a sort of modal wizard. I was able to "fix" this by changing the name property of button (line 202) to button.html() instead of button.text() then write it as button.html() instead of button.text() (line 370). Is this something that could get patched into the trunk?

**Comment by nikku** [comment]
Could you submit a pull request for that?

**Comment by TomCrowley** [comment]
I submitted a pull request. This is my first one on Github so if I did something wrong let me know.
