### ISSUE TITLE
Overlapped links and text

### ISSUE THREAD

**Issue by bhaugen** [nikku/jquery-bootstrap-scripting#7]
Using Chrome 13.0.782.220 on Ubuntu 10.04, I see a lot of overlapped text and links on http://nikku.github.com/jquery-bootstrap-scripting/ 

I used to see that on http://twitter.github.com/bootstrap/ too, but they apparently cleaned that up.  Do you know what causes that set of problems, and how to avoid?

**Comment by nikku** [comment]
Could you post a screenshot of the issues?
Tested Chrome under Windows and everything works. Maybe i have to update the bootstrap library.

**Comment by bhaugen** [comment]
On Fri, Sep 9, 2011 at 9:55 AM, Nico Rehwaldt
reply@reply.github.com
wrote:

> Could you post a screenshot of the issues?

Couldn't figure out how to post the screenshot directly on github.
Trying with an attachment from gmail...

**Comment by bhaugen** [comment]
Attachment did not work.  Here:
http://www.flickr.com/photos/24168943@N00/6130461530/in/photostream

**Comment by nikku** [comment]
Ok, thanks for the hint. I will update the bootstrap styles packaged with this plugin and see if that helps.

A quick fix for you could be to use the new bootstrap css styles along with the plugin. (Can not guarantee that it would work though).

**Comment by nikku** [comment]
May be fixed now on the samples page.
Could you check it and report back? I updated the bootstrap styles used to the latest version.

**Comment by bhaugen** [comment]
Fixed.
