### ISSUE TITLE
POST vs GET for initial load from server

### ISSUE THREAD

**Issue by davidcarroll** [nikku/jquery-bootstrap-scripting#70]
It would be good if the following code would cause the contents to be loaded via POST but this does not work, it uses GET regardless.

``` javascript
        var href = $(this).attr("href");
        $('<div/>').dialog2({
            id: "edit-address",
            content: href,
            type: "POST"
        });
```

I did examine the code and found the ajax call and there is a variable called type, but it is a local var that is never set. See the following:

https://github.com/Nikku/jquery-bootstrap-scripting/blob/master/lib/jquery.dialog2.js#L742-L770

note line 748 where the type variable is declared and line 762 where it is used

I would suggest that `options.type` is passed in to the `load` and then to the `dialogLoad` functions.

**Comment by nikku** [comment]
Hi David, 

what you propose is something you are not allowed to do by accessing a resource via a ´<a href="..." />´, either. That is why I will not support that feature in the library. 

You can always think about performing a post operation via AJAX and displaying the dialog on top of the results.
