### ISSUE TITLE
Vertical scrollbar appears when using with bootstrap 2.3.2

### ISSUE THREAD

**Issue by ssh222** [nikku/jquery-bootstrap-scripting#73]
It seems that there is a problem when using with bootstrap 2.3.2 css. 
Vertical scrollbar appears in the modal body. This problem occurs only when loading data via ajax. There is no such problem when creating in page dialogs. 
Steps to reproduce:
Open this link: http://sandbox.console.dosefun.com/s.html

Any help will be highly appreciated!

**Comment by nikku** [comment]
Please reopen if this is still an issue. Link is dead as far as I can see.

**Comment by dragonfly4** [comment]
I had the issue with bootstrap v3 using AJAX calls
Add this in your CSS to remove it when it's not needed

.modal {
overflow-y: auto;
}
