### ISSUE TITLE
Action buttons on reload

### ISSUE THREAD

**Issue by syphernl** [nikku/jquery-bootstrap-scripting#9]
If you reload the window, with the same content, during the second load you will immediately see the content but the custom buttons show up later.

Is there a way to fix this somehow?

**Comment by nikku** [comment]
Hmm, could you create a scenario for that to make me able to reproduce it?

**Comment by syphernl** [comment]
Its not really that hard :-) 
If you have a popup with custom action buttons (via the class), let the popup content load, close it by either clicking next to it or by hitting the cancel/close button and reopening it.

The (ajax) content will be there still, loading image is shown and then the buttons suddenly appear.

**Comment by nikku** [comment]
Sounds easy to fix ;-)

**Comment by nikku** [comment]
I fixed the issue by clearing the contents of an ajax dialog when it is initially created.
The problem was, that the contents of the dialog are still the old ones, when it re-opened.
